source "https://rubygems.org"

ruby "3.3.5"

gem "rails", "~> 7.1.5", ">= 7.1.5.2"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "devise"
gem "pundit"
gem 'simple_token_authentication'
gem 'jbuilder'

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
end